# Generated by Django 3.0.3 on 2020-03-31 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg_code', models.CharField(max_length=200)),
                ('block_no', models.CharField(max_length=200)),
                ('room_no', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('B', 'Bench'), ('T', 'Tube Light'), ('F', 'Fan'), ('C', 'Class Board'), ('S', 'Switch Board'), ('P', 'Projectors'), ('T', 'Table'), ('A', 'Almirah'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('CIVIL', 'CIVIL'), ('IT', 'IT'), ('M', 'MISCELLANEOUS')], max_length=100)),
                ('asset_no', models.CharField(max_length=20)),
                ('unique_id', models.CharField(max_length=50, verbose_name='clg_code/block_no/room_no/asset_type/asset_no')),
                ('description_asset', models.TextField(blank=True, verbose_name='Describe the asset if it is not clearly mentioned')),
                ('price', models.IntegerField(blank=True, max_length=100)),
                ('is_classroom', models.BooleanField(blank=True)),
                ('is_lab', models.BooleanField(blank=True)),
                ('is_staffroom', models.BooleanField(blank=True)),
                ('is_other', models.BooleanField(blank=True)),
                ('description_room', models.TextField(blank=True, verbose_name='Describe the Room if it is not clearly mentioned')),
                ('date_of_purchase', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('manufacturing_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('warranty_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
