# Generated by Django 3.0.3 on 2020-03-31 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
