# Generated by Django 3.0.3 on 2020-04-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='room_id',
            new_name='asset_id',
        ),
    ]
